homepage_route: "home"
routes:
    home: "Main:home"
    login: 'Main:login'
    createAccount: 'Main:createAccount'
    disconnect:  'Main:disconnect'
    validEmail: 'Main:validEmail'
    validated: 'Main:validated'
    passwordForgoten: 'Main:passwordForgoten'
    changePassword: 'Main:changePassword'
    modifyDataBase: 'Admin:modifyDataBase'
    deleteUser: 'Admin:deleteUser'
    actualithe: 'Main:actualithe'
    history: 'Main:history'
    profile: 'User:profile'
    editProfile: 'User:editProfile'
    addArticle: 'Moderator:addArticle'
    modifyArticle: 'Moderator:modifyArticle'
    bo: 'Admin:bo'