homepage_route: "home"
routes:
    home: "Main:home"
    login: 'Main:login'
    createAccount: 'Main:createAccount'
    disconnect:  'Main:disconnect'
    validEmail: 'Main:validEmail'
    validated: 'Main:validated'